name: todo_app
description: A Flutter Todo Application

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  intl: ^0.17.0
  flutter_local_notifications: ^19.0.0
  logging: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
  flutter_driver:
    sdk: flutter
  test: ^1.16.0


flutter:
  uses-material-design: true
  